# Purpose 

This notebook is meant to quickly understand why the decoding algorithm / other part of the pipeline didn't work for a particular subject / run, using the trigger channels, identifying the bad channels, etc..

In [40]:
# Imports

import mne
import mne_bids
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
mne.set_log_level(False)
import time
import os


%matplotlib inline

In [66]:
# CONST DEFINITION

subject_to_debug = '12'
bids = Path("/home/is153802/workspace_LPP/data/MEG/LPP/BIDS_final")
TASK = 'listen'

In [67]:
bids_path = mne_bids.BIDSPath(
                subject=subject_to_debug,
                session='01',
                task=TASK,
                datatype="meg",
                root=bids,
                run = '06'
            )

print(bids_path)
raw_bids = mne_bids.read_raw_bids(bids_path)

raw_bids.load_data()

/home/is153802/workspace_LPP/data/MEG/LPP/BIDS_final/sub-12/ses-01/meg/sub-12_ses-01_task-listen_run-06_meg.fif


/tmp/ipykernel_346973/1291375337.py:11: RuntimeWarning: This file contains raw Internal Active Shielding data. It may be distorted. Elekta recommends it be run through MaxFilter to produce reliable results. Consider closing the file and running MaxFilter on the data.
  raw_bids = mne_bids.read_raw_bids(bids_path)
/tmp/ipykernel_346973/1291375337.py:11: RuntimeWarning: Did not find any events.tsv associated with sub-12_ses-01_task-listen_run-06.

The search_str was "/home/is153802/workspace_LPP/data/MEG/LPP/BIDS_final/sub-12/**/meg/sub-12_ses-01*events.tsv"
  raw_bids = mne_bids.read_raw_bids(bids_path)
/tmp/ipykernel_346973/1291375337.py:11: RuntimeWarning: The unit for channel(s) STI001, STI002, STI003, STI004, STI005, STI006, STI007, STI008, STI009, STI010, STI011, STI012, STI013, STI014, STI015, STI016, STI101, STI201, STI301 has changed from V to NA.
  raw_bids = mne_bids.read_raw_bids(bids_path)


<Raw | sub-12_ses-01_task-listen_run-06_meg.fif, 329 x 758000 (758.0 s), ~1.86 GB, data loaded>

In [68]:
events = mne.find_events(raw_bids, stim_channel='STI101', shortest_event=1)
print(events)

[[ 17501      0      1]
 [ 20843      0    128]
 [ 21013      0    128]
 ...
 [764356      0    128]
 [764496      0    128]
 [768099      0      1]]
