# Purpose 

This notebook is meant to quickly understand why the decoding algorithm / other part of the pipeline didn't work for a particular subject / run, using the trigger channels, identifying the bad channels, etc..

In [69]:
# Imports

import mne
import mne_bids
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
mne.set_log_level(False)
import time
import os


%matplotlib inline

In [70]:
# CONST DEFINITION

subject_to_debug = '18'
bids = Path("/home/is153802/workspace_LPP/data/MEG/LPP/BIDS_final")
TASK = 'listen'

In [91]:
bids_path = mne_bids.BIDSPath(
                subject=subject_to_debug,
                session='01',
                task=TASK,
                datatype="meg",
                root=bids,
                run = '01'
            )

print(bids_path)
raw_bids = mne_bids.read_raw_bids(bids_path)

raw_bids.load_data()

/home/is153802/workspace_LPP/data/MEG/LPP/BIDS_final/sub-18/ses-01/meg/sub-18_ses-01_task-listen_run-01_meg.fif


/tmp/ipykernel_346973/3479951267.py:11: RuntimeWarning: This file contains raw Internal Active Shielding data. It may be distorted. Elekta recommends it be run through MaxFilter to produce reliable results. Consider closing the file and running MaxFilter on the data.
  raw_bids = mne_bids.read_raw_bids(bids_path)
/tmp/ipykernel_346973/3479951267.py:11: RuntimeWarning: Did not find any events.tsv associated with sub-18_ses-01_task-listen_run-01.

The search_str was "/home/is153802/workspace_LPP/data/MEG/LPP/BIDS_final/sub-18/**/meg/sub-18_ses-01*events.tsv"
  raw_bids = mne_bids.read_raw_bids(bids_path)
/tmp/ipykernel_346973/3479951267.py:11: RuntimeWarning: The unit for channel(s) STI101, STI201, STI301 has changed from V to NA.
  raw_bids = mne_bids.read_raw_bids(bids_path)


KeyboardInterrupt: 

In [ ]:
events = mne.find_events(raw_bids, stim_channel='STI101', shortest_event=1)
print(events)

[[202945      0      1]
 [206269      0    128]
 [206379      0    128]
 ...
 [846937      0    128]
 [847458      0    128]
 [850604      0      1]]


In [ ]:
epochs = mne.Epochs(raw_bids, events, 
                    tmin=-.3, tmax=.8, decim=10, baseline=(-0.2, 0.0))

/tmp/ipykernel_346973/2143477150.py:1: RuntimeWarning: The measurement information indicates a low-pass frequency of 330.0 Hz. The decim=10 parameter will result in a sampling frequency of 100.0 Hz, which can cause aliasing artifacts.
  epochs = mne.Epochs(raw_bids, events,


In [ ]:
epochs.info['nchan']

346

In [ ]:
epochs.info

<Info | 25 non-empty values
 acq_pars: ACQch001 110113 ACQch002 110112 ACQch003 110111 ACQch004 110122 ...
 bads: []
 ch_names: MEG0113, MEG0112, MEG0111, MEG0122, MEG0123, MEG0121, MEG0132, ...
 chs: 204 Gradiometers, 102 Magnetometers, 19 Stimulus, 2 EOG, 1 ECG, 18 misc
 custom_ref_applied: False
 description: Anonymized using a time shift to preserve age at acquisition
 dev_head_t: MEG device -> head transform
 dig: 61 items (3 Cardinal, 4 HPI, 54 Extra)
 events: 1 item (list)
 experimenter: mne_anonymize
 file_id: 4 items (dict)
 highpass: 0.0 Hz
 hpi_meas: 1 item (list)
 hpi_results: 1 item (list)
 hpi_subsystem: 3 items (dict)
 line_freq: 50.0
 lowpass: 330.0 Hz
 maxshield: True
 meas_date: 2022-10-04 12:16:22 UTC
 meas_id: 4 items (dict)
 nchan: 346
 proc_history: 1 item (list)
 proj_id: 1 item (ndarray)
 proj_name: mne_anonymize
 projs: generated with dossp-2.1: on, generated with dossp-2.1: on, ...
 sfreq: 100.0 Hz
 subject_info: 4 items (dict)
>

In [94]:
file1= '/home/is153802/data/BIDS_final/sub-18/ses-01/meg/sub-18_ses-01_task-listen_run-01_meg.fif'
file
fif_321 = mne.io.read_raw_fif(file1,allow_maxshield=True)

/tmp/ipykernel_346973/3726710940.py:1: RuntimeWarning: This file contains raw Internal Active Shielding data. It may be distorted. Elekta recommends it be run through MaxFilter to produce reliable results. Consider closing the file and running MaxFilter on the data.
  fif_321 = mne.io.read_raw_fif('/home/is153802/data/BIDS_final/sub-18/ses-01/meg/sub-18_ses-01_task-listen_run-01_meg.fif',allow_maxshield=True)


In [97]:
fif_321.add_channels()

TypeError: UpdateChannelsMixin.add_channels() missing 1 required positional argument: 'add_list'